### ISSUE TITLE
Add cp437 characters

### ISSUE THREAD

**Issue by davelab6** [googlefonts/Inconsolata#13]
@tracker1 posted in https://github.com/google/fonts/issues/1047: 

It would be really nice to have the missing translated characters for CP437 to unicode[1] added (namely shaded blocks, box,, and other "drawing" characters), which would aid in making this a more useful font for web-based terminal emulators.

I did not go through to identify all the missing characters, but did notice quite a few that were missing.

```
0xb0	0x2591	#LIGHT SHADE
0xb1	0x2592	#MEDIUM SHADE
0xb2	0x2593	#DARK SHADE
...
0xdb	0x2588	#FULL BLOCK
0xdc	0x2584	#LOWER HALF BLOCK
0xdd	0x258c	#LEFT HALF BLOCK
0xde	0x2590	#RIGHT HALF BLOCK
0xdf	0x2580	#UPPER HALF BLOCK
```

[1] ftp://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/PC/CP437.TXT

**Comment by davelab6** [comment]
@tracker1 https://github.com/adobe-type-tools/box-drawing might help with this

**Comment by tracker1** [comment]
@davelab6 I know absolutely nothing of font editing... only know that I'd love to use this as a terminal/web font, but the missing drawing/block and other cp-437 characters make it a non-starter for me.  :-(

**Comment by davelab6** [comment]
@tracker1 cool - thanks for the suggestion :)

**Comment by alexeiva** [comment]
Here you go @tracker1 : https://github.com/cyrealtype/Inconsolata/commit/c7430fc7bd97410c43ebfed07cb52dfb7f830887
![screen shot 2017-07-18 at 1 41 09 pm](https://user-images.githubusercontent.com/16634089/28313228-c7b8e46e-6bbe-11e7-8a00-f6995bb18203.png)
![screen shot 2017-07-18 at 1 41 04 pm](https://user-images.githubusercontent.com/16634089/28313229-c88cf2d6-6bbe-11e7-987b-3b90e4794f2b.png)

Meanwhile, I made box-drawing work for Glyphs v.2.
https://github.com/adobe-type-tools/box-drawing/pull/5/commits/407f204b2a1ced3dabcccfb9e69b00629c01e111

**Comment by tracker1** [comment]
@alexeiva  Nice, thank you so much!

**Comment by tracker1** [comment]
It looks like some of the characters aren't lining up, and that the charaters with lower hanging parts (p, q, y, etc) will overlap the box characters, and that the size of some of the characters aren't the same as the text.  Will try to give this a closer look over the weekend, for html rendering some ansi/ascii files, to see how it works in that case.

**Comment by alexeiva** [comment]
Please post them here. This was a no-brainer script solution. Would be
better to tailor the whole set to match the font metrics based on your
input. Simply by a proportional scale down.


On Jul 24, 2017 22:09, "Michael J. Ryan" <notifications@github.com> wrote:

It looks like some of the characters aren't lining up, and that the
charaters with lower hanging parts (p, q, y, etc) will overlap the box
characters, and that the size of some of the characters aren't the same as
the text. Will try to give this a closer look over the weekend, for html
rendering some ansi/ascii files, to see how it works in that case.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cyrealtype/Inconsolata/issues/13#issuecomment-317524519>,
or mute the thread

**Comment by alexeiva** [comment]
New bug detected: width of cp437 chars is `600` but should be `500`

**Comment by davelab6** [comment]
@appsforartists would you be interested in resolving this? :D

**Comment by pdevine** [comment]
What version of Inconsolata is going to have these?  Just tried 2.000 and they're missing.

**Comment by smasher164** [comment]
Here is a test case that comes across when using Inconsolata in my work. For this text:
```
┌───────┬───────────────┬──────────────────────┐
│  sign │  combination  │ trailing significand │
├───────┼───────┬───────┼──────────────────────┤
│   1   │   5   │   6   │          20          │
└───────┴───────┴───────┴──────────────────────┘
```
I get the desired behavior from Menlo:
![wantBox](https://user-images.githubusercontent.com/12636891/66263974-ad650680-e7ca-11e9-844d-798999f4fd4c.png)
But not from Inconsolata:
![gotBox](https://user-images.githubusercontent.com/12636891/66263973-ad650680-e7ca-11e9-8d7f-531cf179e1bc.png)

**Comment by tracker1** [comment]
#31 is tracking the scale/spacing issues.

**Comment by raphlinus** [comment]
Yup, looking forward to fixing these. Probably next week.

**Comment by pdevine** [comment]
@raphlinus does your change fix all of these issues?
<img width="446" alt="Screen Shot 2019-12-12 at 9 20 24 AM" src="https://user-images.githubusercontent.com/75239/70734576-59dad180-1cc1-11ea-959f-624516202de1.png">

This was using Inconsolata 2.00 using Regular 10pt. If you have Docker on your machine, you can test this out with the command `docker run -it --rm pdevine/textinvaders`.

**Comment by raphlinus** [comment]
@pdevine I wouldn't expect it to reduce the line spacing; this might be a consequence of the terminal using usWin metrics rather than typo metrics (see #35). I will create a "terminal" version of Inconsolata that reduces the usWin metrics as a workaround, but the longer term answer is to fix the software. I do expect the new release to address the block misalignment, but that also depends on whether the font has coverage for all characters used by the space invaders game.

I don't have Docker handy, and in general prefer people to test their use cases with the candidate fonts - just now merged to master, btw.

**Comment by pdevine** [comment]
@raphlinus no worries. That was taken using Apple's "Terminal" which does seem to suffer from the problem. iTerm2 does seem to be better in that regard.

**Comment by smasher164** [comment]
First of all, thank you so much for adding these characters!
I am however seeing some of the lines exhibit uneven thickness when connected. This makes for a pattern-like effect instead of a straight line. Is it possible to address this?
![image](https://user-images.githubusercontent.com/12636891/70754773-0b035b00-1d06-11ea-925e-85e4000e0a8f.png)
![image](https://user-images.githubusercontent.com/12636891/70754788-15bdf000-1d06-11ea-9997-4d51a7bfc256.png)

**Comment by raphlinus** [comment]
I don't think it would be straightforward, it's probably a function of your font renderer. One thing you can do is experiment with other fonts and see if they handle this better, then I could take a look and see what they do.

**Comment by smasher164** [comment]
On further evaluation, it looks to be renderer-dependent like you said. Chrome is giving me different behavior than sublime for the same fonts/sizes.
