### ISSUE TITLE
Current release and plans?

### ISSUE THREAD

**Issue by cprivite** [googlefonts/Inconsolata#33]
So the Readme.md file here shows the changelog for verisons 2.001, 2.011, and 2.013.
The Release list here only has 2.000 listed as a release, and 2.012 as a pre-release. 
The actual Google Font repository has 2.001 committed to it (https://github.com/google/fonts/pull/714). 
The google font page for Inconsolata gives users version 2.000. 

So I have a few questions:
Which is the current produciton version of this font? Can someone get all these things in sync? Any idea when the newer 2.013+ versions will get pushed to the main github and/or website? 

I'm asking as I'm trying to maintain this font on chocolatey and would like to get the best version up there for everyone, but only if it's ready for prime time.

**Comment by svipas** [comment]
I guess we should ask @raphlinus since he created the font.

I have several questions too:

1. There are 2 repos where we can download the font: https://github.com/google/fonts/tree/master/ofl/inconsolata and https://github.com/googlefonts/Inconsolata (this one). So which one is true source of latest and which one will receive future updates?

2. As I understand @raphlinus is creator of font, but font is also updated by @alexeiva, so you're both working on it?

3. I see version `2.012` contains ligatures, but it's also pre-release and enabling ligatures in text editor like VS Code `fi` looks like ligature which is wrong. Also, is @raphlinus okay with them being added because after reading https://github.com/googlefonts/Inconsolata/issues/21 first post where he emailed @davelab6 it looks like he isn't happy with that? But maybe I misunderstood something?

4. What is really weird, there's `2.013` version mentioned in `README` which says ligatures for `fi` and `fl` are removed, but there's no release with that version.

5. As far as I understand this font is being updated and it will be maintained? I saw @raphlinus is doing some work which will be released?

Anyways, I really appreciate work by any people which is involved into this project. This font is really good and I'm thinking of using it. I know this is a free open-sourced font and as I said I appreciate everything is done here, but personally for me it's a little bit unclear about the future of this font and what is currently happening.

**Comment by fidalgo** [comment]
Since the person that created the releases @alexeiva is not active on github anymore, but @raphlinus had made some merges, so let's hope he can do a release. 
@raphlinus can you comment on this?

**Comment by alexeiva** [comment]
@fidalgo I am active on github, but not on Inconsolata.

**Comment by cprivite** [comment]
Sounds like we have to get Google Fonts to assign a new maintainer then?

**Comment by raphlinus** [comment]
I'm working on a major update and will do a release within the next couple of weeks. So far I've been fairly quiet on my development, but you can track the work in, currently, the autofix branch. Over the next few days I'll do some review of the outstanding issues, including vertical metrics.

**Comment by cprivite** [comment]
Oh ok, thanks @raphlinus. Will the vertical metrics work help with the issues using the latest versions on PuTTy (large spaces between lines)?

**Comment by raphlinus** [comment]
I hope so, yes. It would help if somebody were to do the research about what's going wrong there and how best to fix it, but I can also do this myself.

**Comment by cprivite** [comment]
Sounds good, I think that answers my questions.
